[package]
name = "serialize_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"

[dev-dependencies]
serialize_macro_traits = { path = "../serialize_macro_traits" }